INSERT INTO
   `data` (
        `id`,
        `banner`,
        `cover`,
        `icons`,
        `title`,
        `author`,
        `label`,
        `category`,
        `code`,
        `url`,
        `shinopsis`,
        `description`,
        `created_at`,
        `updated_at`,
        `favorite`,
        `auth`
    )
VALUES (
        1,
        'banner1.jpg',
        'cover1.jpg',
        'icon1.png',
        'The Great Mage Returns',
        'John Doe',
        'Fantasy',
        'Manhwa',
        'GRM001',
        'https://example.com/great-mage',
        'Shop1',
        'A powerful mage reincarnates to save the world',
        '2025-01-01 00:00:00',
        '2025-01-02 00:00:00',
        1,
        8
    ),
    (
        2,
        'banner2.jpg',
        'cover2.jpg',
        'icon2.png',
        'Solo Leveling',
        'Chugong',
        'Action',
        'Manhwa',
        'SL002',
        'https://example.com/solo-leveling',
        'Shop2',
        'The story of a weak hunter who becomes the strongest',
        '2024-12-20 00:00:00',
        '2024-12-22 00:00:00',
        1,
        8
    ),
    (
        3,
        'banner3.jpg',
        'cover3.jpg',
        'icon3.png',
        'Attack on Titan',
        'Hajime Isayama',
        'Dark Fantasy',
        'Manga',
        'AOT003',
        'https://example.com/attack-on-titan',
        'Shop3',
        'Humanity fights against monstrous Titans',
        '2024-10-15 00:00:00',
        '2024-11-01 00:00:00',
        1,
        8
    ),
    (
        4,
        'banner4.jpg',
        'cover4.jpg',
        'icon4.png',
        'Demon Slayer',
        'Koyoharu Gotouge',
        'Adventure',
        'Manga',
        'DS004',
        'https://example.com/demon-slayer',
        'Shop4',
        'A boy becomes a demon slayer to save his sister',
        '2024-08-10 00:00:00',
        '2024-08-20 00:00:00',
        1,
        8
    ),
    (
        5,
        'banner5.jpg',
        'cover5.jpg',
        'icon5.png',
        'Tales of Demons and Gods',
        'Mad Snail',
        'Fantasy',
        'Donghua',
        'TDG005',
        'https://example.com/tales-demons',
        'Shop5',
        'A young man travels back in time to save his world',
        '2024-06-25 00:00:00',
        '2024-07-01 00:00:00',
        1,
        8
    ),
    (
        6,
        'banner6.jpg',
        'cover6.jpg',
        'icon6.png',
        'One Piece',
        'Eiichiro Oda',
        'Adventure',
        'Manga',
        'OP006',
        'https://example.com/one-piece',
        'Shop6',
        'A pirate seeks the ultimate treasure',
        '2023-11-11 00:00:00',
        '2023-11-15 00:00:00',
        1,
        8
    ),
    (
        7,
        'banner7.jpg',
        'cover7.jpg',
        'icon7.png',
        'Heaven Officials Blessing',
        'Mo Xiang Tong Xiu',
        'Romance',
        'Donghua',
        'HOB007',
        'https://example.com/heaven-official',
        'Shop7',
        'A love story of a fallen god and a ghost king',
        '2023-10-01 00:00:00',
        '2023-10-05 00:00:00',
        1,
        8
    ),
    (
        8,
        'banner8.jpg',
        'cover8.jpg',
        'icon8.png',
        'Tower of God',
        'SIU',
        'Fantasy',
        'Manhwa',
        'TOG008',
        'https://example.com/tower-of-god',
        'Shop8',
        'A boy climbs a mysterious tower to find his friend',
        '2023-09-15 00:00:00',
        '2023-09-20 00:00:00',
        1,
        8
    ),
    (
        9,
        'banner9.jpg',
        'cover9.jpg',
        'icon9.png',
        'Naruto',
        'Masashi Kishimoto',
        'Action',
        'Manga',
        'NAR009',
        'https://example.com/naruto',
        'Shop9',
        'A ninja strives to become Hokage',
        '2023-08-05 00:00:00',
        '2023-08-10 00:00:00',
        1,
        8
    ),
    (
        10,
        'banner10.jpg',
        'cover10.jpg',
        'icon10.png',
        'The Kings Avatar',
        'Butterfly Blue',
        'E-sports',
        'Donghua',
        'TKA010',
        'https://example.com/kings-avatar',
        'Shop10',
        'A professional gamer returns to reclaim his title',
        '2023-07-01 00:00:00',
        '2023-07-10 00:00:00',
        1,
        8
    );